# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kirrurl',
            name='timestamp',
        ),
    ]
